# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    http_client:
        enabled: true
    php_errors:
        log: true
    serializer:
        enabled: true
        enable_annotations: true
    error_controller: App\Controller\JsonErrorController::show