version: '3.9'

x-php-variables: &php-environment
    environment:
        - SELF_HOST=${SELF_HOST:-https://localhost:80}
        - APP_ENV=${APP_ENV:-dev}
        - APP_DEBUG=${APP_DEBUG:-1}
        - APP_SECRET=${APP_SECRET:-4a4fc495450d79e93c3e00346333a372}
        - NGINX_PUBLIC_PORT=${NGINX_PUBLIC_PORT:-100}
        - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
        - JAWSDB_URL=${APP_DEBUG:-mysql://app:nopassword@mysql/app}
        - MAILER_URL=${MAILER_URL:-smtp://mailhog:1025}
        - POSTGRES_SERVER=${POSTGRES_SERVER:-postgres}
        - POSTGRES_PUBLIC_PORT=${POSTGRES_PUBLIC_PORT:-5436}
        - POSTGRES_DB=${POSTGRES_DB:-app}
        - POSTGRES_VERSION=${POSTGRES_VERSION:-13}
        - POSTGRES_USER=${POSTGRES_USER:-app}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nopassword}
        - DATABASE_URL=${DATABASE_URL:-postgresql://app:nopassword@postgres:5432/app?serverVersion=13&charset=utf8}

services:
    postgres:
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        environment:
          POSTGRES_DB: ${POSTGRES_DB:-app}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nopassword}
          POSTGRES_USER: ${POSTGRES_USER:-app}
        volumes:
          - db-data:/var/lib/postgresql/data:rw

    php:
        build:
          context: .
          dockerfile: ./Dockerfile
          target: app_php
        depends_on:
          - postgres
        volumes:
          - .:/srv/app
          - ./public:/srv/app/public
        <<: *php-environment

    nginx:
        build:
          context: .
          dockerfile: ./Dockerfile
          target: app_nginx
        depends_on:
          - php
        volumes:
          - ./public:/srv/app/public
          - ./var/log/nginx/log:/var/log/nginx

volumes:
  db-data:
