version: "3.9"

x-php-variables: &php-environment
    environment:
        - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
        - APP_ENV=${APP_ENV:-dev}
        - APP_DEBUG=${APP_DEBUG:-1}
        - APP_SECRET=${APP_SECRET:-APPSECRETEDITME}

services:
  nginx:
      ports:
        - ${NGINX_PUBLIC_PORT:-100}:80

  postgres:
      ports:
        - ${POSTGRES_PUBLIC_PORT:-5436}:5432
volumes:
    db_data: {}